# User
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150

# Tag
MAX_LENGTH_TAG_NAME = 32
MAX_LENGTH_TAG_SLUG = 32

# Ingredient
MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_UNIT = 64

# Recipe
MAX_LENGTH_RECIPE_NAME = 254

# RecipeCreateUpdateSerializer
MIN_COOKING_TIME = 1

# Pagination
PAGINATION_PAGE_SIZE = 6
